// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";
import * as ExpoLinearGradient from "expo-linear-gradient";

var styles = ReactNative.StyleSheet.create({
      gradient: {
        flex: 1
      },
      container: {
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      },
      text: {
        color: "rgb(209,62,62)",
        fontSize: 22,
        fontWeight: "500"
      }
    });

function App(Props) {
  return React.createElement(ExpoLinearGradient.LinearGradient, {
              colors: [
                "rgb(10, 13, 47)",
                "rgb(10, 13, 47)"
              ],
              style: styles.gradient,
              start: [
                0.0,
                1.0
              ],
              end: [
                1.0,
                0.0
              ],
              children: React.createElement(ReactNative.View, {
                    style: styles.container,
                    children: React.createElement(ReactNative.Text, {
                          style: styles.text,
                          children: "Build something great! " + " 🤖"
                        })
                  })
            });
}

var make = App;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
